"""
Mode RECORD:
    Create a tmux_state.txt file, recording the current tmux session(s):

        Take the output from
            tmux list-p -aF "#S;#I;#P;#W;#{pane_current_path};#{pane_pid}"
        which is run by the list_tmux_panes method in RECORD mode

        e.g.:
            123;scorpius;1;1;gcloud;/home/kester/Dropbox/gcloud/projects/sf_p3;4190
            123;scorpius;1;2;gcloud;/home/kester/Dropbox/export/apple_health_export;4197
            123;scorpius;2;3;analytics;/home/kester;4221
            123;scorpius;2;4;analytics;/home/kester;169213
            123;scorpius;3;1;meetings;/home/kester;4231
            123;scorpius;4;1;codility;/home/kester/codility;4237
            123;scorpius;5;1;discord_music;/home/kester/Desktop;4248
            123;scorpius;5;2;discord_music;/home/kester/src/ayb-bot;4265
            123;scorpius;5;3;discord_music;/home/kester/src;23582
            123;scorpius;6;1;footpedal;/home/kester;4276
            123;scorpius;7;1;hermes robot protocol docs;/home/kester/src/hermes;4294
            123;scorpius;8;1;bash;/home/kester;299586

        and modify that to include the command that is generating the process ID
        (pane_pid) argument as a new final column (and CSV-ify it):
            123,scorpius,1,1,gcloud,/home/kester/Dropbox/gcloud/projects/sf_p3,4190,vim surlyfritter/scripts/wordle.py
            123,scorpius,1,2,gcloud,/home/kester/Dropbox/export/apple_health_export,4197,
            123,scorpius,2,3,analytics,/home/kester,4221,/home/kester/.virtualenv/twitter/bin/python pgcli -hdbtl.stage.amyris.local -p9999 -Upgdb -dpgdbstage
            123,scorpius,2,4,analytics,/home/kester,169213,
            123,scorpius,3,1,meetings,/home/kester,4231,vim notes/meeting_notes.txt
            123,scorpius,4,1,codility,/home/kester/codility,4237,
            123,scorpius,5,1,discord_music,/home/kester/Desktop,4248,
            123,scorpius,5,2,discord_music,/home/kester/src/ayb-bot,4265,vim ayb-bot/bot.py
            123,scorpius,5,3,discord_music,/home/kester/src,23582,
            123,scorpius,6,1,footpedal,/home/kester,4276,vim /home/kester/src/javascript_timing.html
            123,scorpius,7,1,hermes robot protocol docs,/home/kester/src/hermes,4294,
            123,scorpius,8,1,bash,/home/kester,299586,

        Generated by this cronjob:
            tmux list-s && python3 tmux_state.py record

or

Mode RESTORE:
    Read a tmux_state.txt file and generate a script to recreate the tmux
    session(s) for which the state files was recorded.


"""

from collections import defaultdict
import contextlib
import csv
import os
import subprocess
import sys
from typing import ClassVar

from pydantic import BaseModel

OUTPUT_COMMAND_INDEX = -1  # ?
SPLIT_CHAR = ";"
DEFAULT_STATE_FILE = "~/tmux_state.txt"

RECORD = "record"
RESTORE = "restore"
ALLOWED_MODES = (RECORD, RESTORE)


class Pane(BaseModel):
    """
    Lists of this object should be sorted by session_creation_id, window_index, pane_index
    """
    session_creation_id: str
    session: str
    window_index: int
    pane_index: int
    window_name: str
    cwd: str
    ppid: int
    command: str

    # Class variables to list the panes. Note that the list format
    # (list_command[2]) # must exactly correspond to Pane's instance variables
    # (.sessions, .window_index, etc.) and be in the same order
    list_command: ClassVar[list[str]] = [
        "list-panes",
        "-aF",
        "#{session_created};#S;#I;#P;#W;#{pane_current_path};#{pane_pid}",
    ]
    ppid_index: ClassVar[int] = -1

    @property
    def i_sw(self):
        return f"{self.session}:{self.window_index}"

    @property
    def i_swp(self):
        return f"{self.session}:{self.window_index}.{self.pane_index}"

    @classmethod
    def from_row(cls, row: str) -> "Pane":
        names = Pane.model_fields.keys()
        values = list(csv.reader([row]))[0]
        assert len(names) == len(values)
        model_data = {nv[0]: nv[1] for nv in zip(names, values)}
        return cls.model_validate(model_data)


def read_state_file(state_file) -> defaultdict:
    """
    Read a tmux state file generated by
        python3 tmux_state_record.py >| ~/tmux_state.txt
    and generate a tmux state list-of-panes). Note that panes contain complete
    window and session information.
    """
    with open(state_file, encoding="utf-8") as tmux_states:
        pane_rows = [r.rstrip("\n") for r in tmux_states if not r.startswith("#")]
        # (Skip commented-out rows)
        panes = [Pane.from_row(row) for row in pane_rows]

    if not panes:
        raise ValueError(f"No state read from {state_file} in read_state_file")

    return sorted(panes, key=lambda p: (p.session_creation_id, int(p.window_index), int(p.pane_index)))


def generate_commands(panes: list[Pane]):
    sessions_created = set()
    commands = []
    for ipane, pane in enumerate(panes):

        # Create a new session and detach (for now) if it doesn't already
        # exist. If it does, have the tmux restore script exit with a warning
        # Manually name the first sessions's inital window
        #
        # The pane should be split if its window index is different from
        # the previous pane's (this relies on the sorting of the panes list).
        # The first pane ever can't be a split pane, and a split pane doesn't rename
        # the window, so an if/else/if/else is used here.
        #
        is_first_pane_in_session = pane.session not in sessions_created
        if is_first_pane_in_session:
            warning = f"session '{pane.session}' already exists, quitting"
            commands.append(f'has-session -t "{pane.session}" 2> /dev/null && echo "{warning}" && exit 1')
            sessions_created.add(pane.session)

            command = f'new-session -s "{pane.session}" -n "{pane.window_name}" -d -c "{pane.cwd}"'
            t_arg = f'-t "{pane.i_sw}"'
        else:
            # If this pane is in a new window, create that window (this also
            # the pane). If this pane is part of an existing window, split that
            # window to create the pane:
            #
            is_split_pane = (
                pane.window_index == panes[ipane - 1].window_index
                and pane.session == panes[ipane - 1].session
            )
            if is_split_pane:
                command = f'split-window -t "{pane.i_sw}" -h -c "{pane.cwd}"'
                t_arg = f'-t "{pane.i_swp}"'
            else:
                command = f'new-window -t "{pane.session}:" -n "{pane.window_name}" -c "{pane.cwd}"'
                t_arg = f'-t "{pane.i_sw}"'

        commands.append(command)
        if pane.command:
            #command += f' "{pane.command}"; bash'
            commands.append(f'send-keys {t_arg} "{pane.command}" C-m')


    commands.append(f'attach -t "{panes[0].session}"')

    return commands


def command_from_ppid(ppid: str, command_index: int = OUTPUT_COMMAND_INDEX) -> str:
    """
    Get the command corresponding to the PPID from #{pane_pid} in the tmux list-p

    Grab only the command_index-th PID output if there are multiple PIDs for this pane,
    e.g. one or more suspended jobs in the pane
    """
    ps_command = ["ps", "-hoargs", "--ppid", ppid]
    ps_output = subprocess.run(ps_command, capture_output=True, check=False)
    commands = ps_output.stdout.decode("utf-8").rstrip().split("\n")
    command = commands[command_index]
    return command


def list_tmux_panes() -> list[str]:
    """Record current state"""
    list_panes_cmd = ["tmux"] + Pane.list_command
    list_panes_output = subprocess.run(list_panes_cmd, capture_output=True, check=False)
    list_panes_output_rows = (
        list_panes_output.stdout.decode("utf-8").rstrip().split("\n")
    )
    panes = []
    for pane_row in list_panes_output_rows:
        pane = pane_row.rstrip().split(SPLIT_CHAR)
        pane_command = command_from_ppid(ppid=pane[Pane.ppid_index])
        pane.append(pane_command)
        panes.append(pane)
    return panes


@contextlib.contextmanager
def open_output(path=None):
    """
    Opens either a file or stdout for writing
    Used to to ensure that CSV module usage is concise.
    """
    if path:
        with open(path, "w") as f:
            yield f
    else:
        yield sys.stdout


def main() -> None:
    """Read the state file and generate the recreate-the-state bash script."""

    mode = sys.argv[1] if len(sys.argv) > 1 else RECORD
    state_file = sys.argv[2] if len(sys.argv) > 2 else DEFAULT_STATE_FILE
    state_file = os.path.expanduser(state_file)

    if mode not in ALLOWED_MODES:
        raise ValueError(f"mode {mode} isn't supported, must be one of {ALLOWED_MODES}")

    if mode == RECORD:
        tmux_panes = list_tmux_panes()
        with open_output(state_file) as file:
            csv.writer(file).writerows(tmux_panes)

    if mode == RESTORE:
        panes = read_state_file(state_file)
        print("set -e")
        for command in generate_commands(panes):
            print(f"tmux {command}")


if __name__ == "__main__":
    main()
