"""
Mode RECORD:
    Create a tmux_state.txt file, recording the current tmux session(s):

        Take the output from
            tmux list-p -aF "#S;#I;#P;#W;#{pane_current_path};#{pane_pid}"
        which is run by the list_tmux_panes method in RECORD mode

        e.g.:
            scorpius;1;1;gcloud;/home/kester/Dropbox/gcloud/projects/sf_p3;4190
            scorpius;1;2;gcloud;/home/kester/Dropbox/export/apple_health_export;4197
            scorpius;2;3;analytics;/home/kester;4221
            scorpius;2;4;analytics;/home/kester;169213
            scorpius;3;1;meetings;/home/kester;4231
            scorpius;4;1;codility;/home/kester/codility;4237
            scorpius;5;1;discord_music;/home/kester/Desktop;4248
            scorpius;5;2;discord_music;/home/kester/src/ayb-bot;4265
            scorpius;5;3;discord_music;/home/kester/src;23582
            scorpius;6;1;footpedal;/home/kester;4276
            scorpius;7;1;hermes robot protocol docs;/home/kester/src/hermes;4294
            scorpius;8;1;bash;/home/kester;299586

        and modify that to include the command that is generating the process ID
        (pane_pid) argument as a new final column (and CSV-ify it):
            scorpius,1,1,gcloud,/home/kester/Dropbox/gcloud/projects/sf_p3,4190,vim surlyfritter/scripts/wordle.py
            scorpius,1,2,gcloud,/home/kester/Dropbox/export/apple_health_export,4197,
            scorpius,2,3,analytics,/home/kester,4221,/home/kester/.virtualenv/twitter/bin/python pgcli -hdbtl.stage.amyris.local -p9999 -Upgdb -dpgdbstage
            scorpius,2,4,analytics,/home/kester,169213,
            scorpius,3,1,meetings,/home/kester,4231,vim notes/meeting_notes.txt
            scorpius,4,1,codility,/home/kester/codility,4237,
            scorpius,5,1,discord_music,/home/kester/Desktop,4248,
            scorpius,5,2,discord_music,/home/kester/src/ayb-bot,4265,vim ayb-bot/bot.py
            scorpius,5,3,discord_music,/home/kester/src,23582,
            scorpius,6,1,footpedal,/home/kester,4276,vim /home/kester/src/javascript_timing.html
            scorpius,7,1,hermes robot protocol docs,/home/kester/src/hermes,4294,
            scorpius,8,1,bash,/home/kester,299586,

        Generated by this cronjob:
            tmux list-s && python3 tmux_state.py record
or

Mode RESTORE:
    Read a tmux_state.txt file and generate a script to recreate the tmux
    session(s) for which the state files was recorded.


"""

from collections import defaultdict
import contextlib
import csv
import os
import subprocess
import sys
from typing import ClassVar

from pydantic import BaseModel

OUTPUT_COMMAND_INDEX = -1  # ?
SPLIT_CHAR = ";"
DEFAULT_STATE_FILE = "~/tmux_state.txt"

RECORD = "record"
RESTORE = "restore"
ALLOWED_MODES = (RECORD, RESTORE)


class Pane(BaseModel):
    session: str
    window_index: int
    pane_index: int
    window_name: str
    cwd: str
    ppid: int
    command: str

    # Class variables to list the panes. Note that the list_format
    # must exactly correspond to Pane's instance variables
    # (.sessions, .window_index, etc.) and be in the same order
    list_command: ClassVar[list[str]] = [
        "list-panes",
        "-aF",
        "#S;#I;#P;#W;#{pane_current_path};#{pane_pid}",
    ]

    @classmethod
    def from_row(cls, row: str) -> "Pane":
        names = Pane.model_fields.keys()
        values = list(csv.reader([row]))[0]
        assert len(names) == len(values)
        model_data = {nv[0]: nv[1] for nv in zip(names, values)}
        return cls.model_validate(model_data)


def read_state_file(state_file) -> defaultdict:
    """
    Read a tmux state file generated by
        python3 tmux_state_record.py  >| ~/tmux_state.txt
    and generate a tmux state dict (session -> list-of-panes) note that panes
    contain complete window information.
    """
    with open(state_file, encoding="utf-8") as tmux_states:
        rows = [r.rstrip("\n") for r in tmux_states if not r.startswith("#")]
        # (Skip commented-out rows)

    state = defaultdict(list)
    for row in rows:
        pane = Pane.from_row(row)
        state[pane.session].append(pane)

    # Ensure that panes are sorted by window index, pane index
    for session in state:
        state[session].sort(key=lambda p: (p.window_index, p.pane_index))

    if not state:
        raise ValueError("No state in read_state_file")

    return state


def generate_commands(state: defaultdict):
    tmux_commands = []
    for session, panes in state.items():
        # If a session already exists, exit with a warning
        warning = f"session '{session}' already exists, quitting"
        tmux_commands.append(
            f"""has-session -t "{session}" && echo "{warning}" && exit 1"""
        )
        tmux_commands.append(f"""new-session -s "{session}" -d""")

        for ipane, pane in enumerate(panes):
            # The pane should be split if its window index is different from
            # the previous pane's. This relies on the fact that the panes list
            # is sorted. The first pane can't be a split pane, and a split pane
            # doesn't rename the window, so an if/else/if/else is used here.
            is_first_pane_in_first_window = ipane == 0

            # Rename the inital window created at session start
            if is_first_pane_in_first_window:
                tmux_command = f'rename-window "{pane.window_name}"'
            else:
                # If a window contains multiple panes, create an additional pane here:
                prev_pane = panes[ipane - 1]
                is_split_pane = pane.window_index == prev_pane.window_index
                if is_split_pane:
                    tmux_command = f"split-window -t {session} -h"
                # For the first pane of a new window, make the window,
                # which implicitly creates the first pane:
                else:
                    tmux_command = f'new-window -n "{pane.window_name}" -t "{session}"'
            tmux_commands.append(tmux_command)

            sendkeys_args = f'-t "{session}:{pane.window_index}.{pane.pane_index}"'
            tmux_commands.append(f"""send-keys {sendkeys_args} "cd '{pane.cwd}'" C-m""")
            if pane.command:
                tmux_commands.append(f'send-keys {sendkeys_args} "{pane.command}" C-m')

    tmux_commands.append(f'attach -t "{next(iter(state))}"')

    return tmux_commands


def command_from_ppid(ppid: int, command_index: int = OUTPUT_COMMAND_INDEX) -> str:
    """
    Get the command corresponding to the PPID from #{pane_pid} in the tmux list-p

    Grab only the command_index-th PID output if there are multiple PIDs for this pane,
    e.g. one or more suspended jobs in the pane
    """
    ps_command = ["ps", "-hoargs", "--ppid", str(ppid)]
    ps_output = subprocess.run(ps_command, capture_output=True, check=False)
    commands = ps_output.stdout.decode("utf-8").rstrip().split("\n")
    command = commands[command_index]
    return command


def list_tmux_panes() -> list[str]:
    list_panes_cmd = ["tmux"] + Pane.list_command
    ps_output = subprocess.run(list_panes_cmd, capture_output=True, check=False)
    panes = ps_output.stdout.decode("utf-8").rstrip().split("\n")
    return panes


@contextlib.contextmanager
def open_output(path=None):
    """Opens either a file or stdout for writing"""
    if path:
        with open(path, "w") as f:
            yield f
    else:
        yield sys.stdout


def write_state_file(destination: str = None) -> None:
    with open_output(destination) as file:
        for tmux_pane in list_tmux_panes():
            pane_info = tmux_pane.rstrip().split(SPLIT_CHAR)
            command = command_from_ppid(ppid=int(pane_info[-1]))
            pane_info.append(command)
            csv.writer(file).writerow(pane_info)


def main() -> None:
    """Read the state file and generate the recreate-the-state bash script."""

    mode = sys.argv[1] if len(sys.argv) > 1 else RECORD
    state_file = sys.argv[2] if len(sys.argv) > 2 else DEFAULT_STATE_FILE
    state_file = os.path.expanduser(state_file)

    if mode not in ALLOWED_MODES:
        raise ValueError(f"mode {mode} isn't supported, must be one of {ALLOWED_MODES}")

    if mode == RECORD:
        write_state_file(state_file)

    if mode == RESTORE:
        state = read_state_file(state_file)
        for tmux_command in generate_commands(state):
            print(f"tmux {tmux_command}")


if __name__ == "__main__":
    main()
