"""
Take the output from
    tmux list-p -aF "#S;#I;#P;#W;#{pane_current_path};#{pane_pid}"

e.g.:
    scorpius;1;1;gcloud;/home/kester/Dropbox/gcloud/projects/sf_p3;4190
    scorpius;1;2;gcloud;/home/kester/Dropbox/export/apple_health_export;4197
    scorpius;2;1;analytics and strainbanking and staging db;/home/kester;4203
    scorpius;2;2;analytics and strainbanking and staging db;/home/kester;4209
    scorpius;2;3;analytics and strainbanking and staging db;/home/kester;4221
    scorpius;2;4;analytics and strainbanking and staging db;/home/kester;169213
    scorpius;3;1;meetings;/home/kester;4231
    scorpius;4;1;codility;/home/kester/codility;4237
    scorpius;5;1;discord_music;/home/kester/Desktop;4248
    scorpius;5;2;discord_music;/home/kester/src/ayb-bot;4265
    scorpius;5;3;discord_music;/home/kester/src;23582
    scorpius;6;1;footpedal;/home/kester;4276
    scorpius;7;1;hermes robot protocol docs;/home/kester/src/hermes;4294
    scorpius;8;1;bash;/home/kester;299586

and modify that to include the command that is generating the process ID
(pane_pid) argument as a new final column (and CSV-ify it):

    scorpius,1,1,gcloud,/home/kester/Dropbox/gcloud/projects/sf_p3,4190,vim surlyfritter/scripts/wordle.py
    scorpius,1,2,gcloud,/home/kester/Dropbox/export/apple_health_export,4197,
    scorpius,2,1,analytics and strainbanking and staging db,/home/kester,4203,
    scorpius,2,2,analytics and strainbanking and staging db,/home/kester,4209,
    scorpius,2,3,analytics and strainbanking and staging db,/home/kester,4221,/home/kester/.virtualenv/twitter/bin/python /home/kester/.virtualenv/twitter/bin/pgcli -hdbtl.stage.amyris.local -p9999 -Upgdb -dpgdbstage
    scorpius,2,4,analytics and strainbanking and staging db,/home/kester,169213,
    scorpius,3,1,meetings,/home/kester,4231,vim notes/meeting_notes.txt
    scorpius,4,1,codility,/home/kester/codility,4237,
    scorpius,5,1,discord_music,/home/kester/Desktop,4248,
    scorpius,5,2,discord_music,/home/kester/src/ayb-bot,4265,vim ayb-bot/bot.py
    scorpius,5,3,discord_music,/home/kester/src,23582,
    scorpius,6,1,footpedal,/home/kester,4276,vim /home/kester/src/javascript_timing.html
    scorpius,7,1,hermes robot protocol docs,/home/kester/src/hermes,4294,
    scorpius,8,1,bash,/home/kester,299586,


Generated by this cronjob:

    tmux list-s && (tmux list-p -aF "#S;#I;#P;#W;#{pane_current_path};#{pane_pid}" | python3 ~/src/tmux_scripts/tmux_state_record.py  >| ~/tmux_state.txt)

Note: the "tmux list-p" command is kludge-semicolon-delimitted, but output from
this script is properly CSV-ed, since the pane_pid will occasionally point to a
command containing semicolons, which breaks the restoration.

"""

import subprocess
import sys
import csv
import io

OUTPUT_COMMAND_INDEX = -1  # ?
SPLIT_CHAR = ";"


def list_to_csv_str(line):
    with io.StringIO() as si:
        csv.writer(si, lineterminator="").writerow(line)
        return si.getvalue()


def command_from_ppid(ppid, command_index=OUTPUT_COMMAND_INDEX):
    """
    Get the command corresponding to the PPID from #{pane_pid} in the tmux list-p

    Grab only the command_index-th PID output if there are multiple PIDs for this pane,
    e.g. one or more suspended jobs in the pane
    """
    ps_command = ["ps", "-hoargs", "--ppid", ppid]
    ps_output = subprocess.run(ps_command, capture_output=True, check=False)
    commands = ps_output.stdout.decode("utf-8").rstrip().split("\n")
    command = commands[command_index]
    return command


def main():
    """Append the command to the tmux state"""
    for line in sys.stdin:
        pane_info = line.rstrip().split(SPLIT_CHAR)
        command = command_from_ppid(ppid=pane_info[-1])
        pane_info.append(command)
        line = list_to_csv_str(pane_info)
        print(line)


if __name__ == "__main__":
    main()
